### ISSUE TITLE
response API use pattern

### ISSUE THREAD

**Issue by davebshow** [davebshow/gremlinclient#1]
@platinummonkey - Which server response API do you prefer for the new client?

aiogremlin uses the following API to get a list of messages:

```python
resp = yield from gc.submit("x + x", bindings={"x": 4})
result = yield from resp.get()
```

But for streaming responses, you do this:

```python
resp = yield from gc.submit("x + x", bindings={"x": 1})
while True:
    result = yield from resp.stream.read()
    if result is None: break
```

For the new client, I was thinking about maintaining the ```response.get``` method while simplifying the streaming to something like this:

```python
resp = yield from gc.submit("x + x", bindings={"x": 1})
while True:
    result = yield from resp.read()
    if result is None: break
```

Thoughts? Do you have a preference?

**Comment by platinummonkey** [comment]
I like it, seems useful and easy to reason about. Will also give other users of this library the option to pick and choose.
