### ISSUE TITLE
InvalidStateError on stream.read() for message with 206 status

### ISSUE THREAD

**Issue by leifurhauks** [davebshow/gremlinclient#11]
`Stream.read` sometimes throws an `InvalidStateError` originating at [connection.py:344](https://github.com/davebshow/gremlinclient/blob/e85228982c316db138995f9bda69dbe91324c954/gremlinclient/connection.py#L344). It seems that sometimes the future is already cancelled at that point, so `future.set_result(message)` raises `InvalidStateError`.

I haven't found a cause yet.

**Comment by davebshow** [comment]
As we determined, this was caused due to a timeout canceling the future.
