### ISSUE TITLE
Runtime Errors on non 2** response

### ISSUE THREAD

**Issue by pmcfadden** [davebshow/gremlinclient#2]
Hey @davebshow first off, thanks for this client it's been really helpful in getting up and going with TP3/Titan1.0

We were having some issues handling the RuntimeError raised as part of GremlinResponse#parser.  It might be we're going about it incorrectly, which I'm still looking into.  However, in the meantime I made an update that will allow you to pass a flag for if you want gremlinclient to not raise the exception, and return the errors/status code in the Message tuple.

Also, it looked like there was a positioning mismatch of message and metadata on the response, so we weren't actually getting the error text from the server.  So we swapped that as well. I didn't know if you preferred an issue before a pull request, but I'll open one as well. 

Thoughts/Ideas/Issues?

**Comment by davebshow** [comment]
This client is super alpha so the error handling hasn't been implemented. I don't know what your use case is, but if you are looking for a more mature library I would check out aiogremlin: http://aiogremlin.readthedocs.org/en/latest/. But if you are using Python 2 or Tornado this one will be a good choice. I'm actually on vacation so I won't really be able to take a close look at this until next week. I'll check out your pull though. Thanks for the interest.

**Comment by pmcfadden** [comment]
Unfortunately/Fortunately we are on Python2.  Yea we knew it was pretty early, we were just glad there was something started already.  No worries, we're pulling it in from my fork right now, so it will keep.  Have a good vacation
