### ISSUE TITLE
How to use library with existing Tornado web app

### ISSUE THREAD

**Issue by emehrkay** [davebshow/gremlinclient#4]
Do you know how to hook into an existing ioloop and retrieve results?

I've been playing around with adding futures via ioloop.add_future and many other, unsuccessful approaches. And you simply cannot run run_sync because it assumes it is the only loop running and throws an error. Any suggestions? 

Thanks,
Mark

**Comment by davebshow** [comment]
`gremlinclient` should be able to integrate smoothly in any Tornado based app. The easiest way to work with the `Futures` returned by gremlinclient is to use coroutines [1]. Here is a basic Tornado web application that submits a "1 + 1" script to the Gremlin Server as an example:

```python
import json

import tornado.ioloop
import tornado.web
from tornado import gen

from gremlinclient import submit


class MainHandler(tornado.web.RequestHandler):

    @gen.coroutine
    def get(self):
        results = []
        resp = yield submit("1 + 1")
        while True:
            msg = yield resp.read()
            if msg is None:
                break
            results.append(msg.data)
        self.write(json.dumps(results))

if __name__ == "__main__":
    application = tornado.web.Application([
        (r"/", MainHandler),
    ])
    application.listen(8888)
    tornado.ioloop.IOLoop.current().start()
```

I hope this helps, if not let me know.

1. http://www.tornadoweb.org/en/stable/guide/coroutines.htm

**Comment by emehrkay** [comment]
Thanks, I managed to fix the issues I was having. I was attempting some craziness where I wanted to use your library as the backbone for my library Gizmo (https://github.com/emehrkay/gizmo), but still wanted to allow blocking calls. I decided against that, everything will be done on the ioloop.

**Comment by emehrkay** [comment]
I think my original question was more along the lines of "how do I utilize gremlinclient in a blocking way?" and I figured that out (for those who want to do it)

~~~python

def blocking(callback, *args, **kwargs):
    from tornado.ioloop import IOLoop
    from tornado import gen

    ioloop = IOLoop(make_current=False)
    r = {'response': ''}

    @gen.coroutine
    def run():
        fut = callback(*args, **kwargs)
        r['response'] = yield gen.maybe_future(fut)
    resp = ioloop.run_sync(run)
    return r['response']

result = blocking(some_function_that_returns_a_future, *args, **kwargs)
~~~

What do you think?

**Comment by davebshow** [comment]
I'm not sure if I understand your example. I think for that use case it would be better to use a HTTP client.

**Comment by emehrkay** [comment]
With that blocking function you could do something like (without having to be in an ioloop):

~~~python
from gremlinclient import submit

response = blocking(submit, gremlin='1+1')
message = blocking(response.read) #this should give you the message namedtuple
~~~

I'm going to take a look at your http client as well.
