### ISSUE TITLE
`log` module hijacks the configuration of the root logger

### ISSUE THREAD

**Issue by leifurhauks** [davebshow/gremlinclient#5]
In `gremlinclient.log`, the [call to `logging.basicConfig`](https://github.com/davebshow/gremlinclient/blob/master/gremlinclient/log.py#L4) makes calls to `logging.basicConfig` a no-op in any client code that (directly or indirectly) imports this module. 

From the docs for [`logging.basicConfig`](https://docs.python.org/3/library/logging.html#logging.basicConfig):
>This function does nothing if the root logger already has handlers configured for it.

Probably better not to force a logging configuration onto the client programmer's root logger!

**Comment by davebshow** [comment]
Thanks @leifurhauks. Feel like making a pull?

**Comment by leifurhauks** [comment]
yep, sorry was sidetracked in the meantime
