### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by seeIT-52** [davebshow/gremlinclient#7]
1. can't use it by reading README.md, could you please update it?
2. in gremlinclient/gremlinclient/tornado_client/client.py, line 220,  the arg 'bindings' is set to None, serious?

**Comment by leifurhauks** [comment]
Thanks for your comments. The second point is easily fixed.

Could you tell us what problem you ran into with the README?

**Comment by davebshow** [comment]
README is out of date. Will update. Please refer to official documentation: http://gremlinclient.readthedocs.org/en/latest/index.html

**Comment by jsenecal** [comment]
Also @seeIT-52 for your second point, next time you have an issue with opensource software make sure to include a [mcve](http://stackoverflow.com/help/mcve) in your issue. Complaining/Commenting the way you did will get you nowhere ;) this is open source software, the community is making it great and nobody owes anyone anything.

**Comment by seeIT-52** [comment]
@davebshow @leifurhauks , many thanks.
This project is very helpful, really appreciate.
And @jsenecal ,thanks for your advice.

**Comment by davebshow** [comment]
No worries!
